name: mmode_testing
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - astropy=3.2.3
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - beautifulsoup4=4.8.1
  - blas=1.0
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - click=7.0
  - cycler=0.10.0
  - cython=0.29.13
  - dbus=1.13.6
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - future=0.17.1
  - gettext=0.19.8.1
  - glib=2.58.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5py=2.9.0
  - hdf5=1.10.4
  - healpy=1.12.10
  - html5lib=1.0.1
  - icu=58.2
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - jpeg=9c
  - jplephem=2.9
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.32
  - lxml=4.4.1
  - matplotlib=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - more-itertools=7.2.0
  - mpi=1.0
  - mpi4py=3.0.3
  - mpich=3.3.1
  - ncurses=6.1
  - numpy=1.17.2
  - numpy-base=1.17.2
  - openssl=1.1.1d
  - packaging=19.2
  - pcre=8.43
  - pip=19.3.1
  - pluggy=0.13.0
  - psutil=5.6.5
  - pthread-stubs=0.4
  - py=1.8.0
  - pyparsing=2.4.4
  - pyqt=5.9.2
  - pytest=5.2.2
  - pytest-arraydiff=0.3
  - pytest-astropy=0.6.0
  - pytest-astropy-header=0.1.1
  - pytest-doctestplus=0.4.0
  - pytest-openfiles=0.4.0
  - pytest-remotedata=0.3.1
  - pytest-runner=5.2
  - python=3.7.5
  - python-dateutil=2.8.1
  - pytz=2019.3
  - qt=5.9.7
  - readline=7.0
  - scipy=1.3.1
  - setuptools=41.6.0
  - sip=4.19.8
  - six=1.12.0
  - skyfield=1.14
  - soupsieve=1.9.4
  - sqlite=3.30.1
  - tk=8.6.8
  - tornado=6.0.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - argh==0.26.2
    - randomgen==1.16.6
    - sgp4==1.4
    - "--editable=git+https://github.com/zhengzhang-univ/caput.git#egg=caput-master"
    - "--editable=git+https://github.com/zhengzhang-univ/cora.git#egg=cora-master"
    - "--editable=git+https://github.com/zhengzhang-univ/driftscan.git#egg=driftscan-master"
    - "--editable=git+https://github.com/zhengzhang-univ/draco.git#egg=draco-master"
    - "--editable=git+https://github.com/zhengzhang-univ/hirax_transfer.git#egg=hirax_transfer-master"
